<Project>

  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <Version>1.4.0</Version>
    <Authors>Mo3bdlaa</Authors>
    <Company>Mo3bdlaa</Company>
    <Product>BusinessTime.Activities</Product>
    <Copyright>Copyright (c) Mo3bdlaa</Copyright>
    <PackageProjectUrl>https://github.com/Mo3bdlaa/BusinessTime.Activities</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Mo3bdlaa/BusinessTime.Activities</RepositoryUrl>
    <NeutralLanguage>en-US</NeutralLanguage>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
  </PropertyGroup>

</Project>
